/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2021-12-13 01:33:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class LoginForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	button {\r\n");
      out.write("		cursor:pointer;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"https://static.nid.naver.com/js/naverLogin_implicit-1.0.3.js\"></script>\r\n");
      out.write("<script src=\"https://developers.kakao.com/sdk/js/kakao.js\"></script>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	\r\n");
      out.write("		$(document).ready(function(){\r\n");
      out.write("			$(\"#mid\").attr('placeholder','아이디');\r\n");
      out.write("			$('#mpw').attr('placeholder','비밀번호');\r\n");
      out.write("			\r\n");
      out.write("			$('#btn').click(function(){\r\n");
      out.write("				console.log(\"btn >>> : \");\r\n");
      out.write("				\r\n");
      out.write("				$(\"#loginForm\").attr({\r\n");
      out.write("					'action':'login.cd',\r\n");
      out.write("					'method':'POST',\r\n");
      out.write("					'enctype':'application/x-www-form-urlencoded'\r\n");
      out.write("				}).submit();\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/include/header.jsp", out, true);
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<form name=\"loginForm\" id=\"loginForm\">\r\n");
      out.write("	<div id=\"contents\" class=\"sub_con\">\r\n");
      out.write("            <div class=\"login_con01 clear\">\r\n");
      out.write("                <div class=\"login\">\r\n");
      out.write("                    <form action=\"\" method=\"get\">\r\n");
      out.write("                        <fieldset>\r\n");
      out.write("                            <legend>로그인</legend>\r\n");
      out.write("                            <h4>CatchDog 이용을 위해 로그인을 해주세요</h4>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                            <li><input type=\"text\" name=\"mid\" id=\"mid\" value=\"\" title=\"아이디 입력\" placeholder=\"이메일 아이디\"></li>\r\n");
      out.write("                            <li><input type=\"password\" name=\"mpw\" id=\"mpw\" value=\"\" title=\"비밀번호 입력\"></li>\r\n");
      out.write("                            <li><button type=\"button\" id=\"btn\">로그인</button></li>\r\n");
      out.write("                            </ul>                        \r\n");
      out.write("                            <div>\r\n");
      out.write("                                <span>아직 회원이 아니신가요?</span><a href=\"memForm.cd\">회원가입</a>\r\n");
      out.write("							    <div id=\"naver_id_login\" style=\"margin-left: -13px; display: inline-block;\"></div>\r\n");
      out.write("							  <!-- //네이버 로그인 버튼 노출 영역 -->\r\n");
      out.write("							  <script type=\"text/javascript\">\r\n");
      out.write("							  	var naver_id_login = new naver_id_login(\"i2N985GdjT6UNzp8kb8g\", \"http://localhost:8088/NaverCallback.cd\");\r\n");
      out.write("							  	var state = naver_id_login.getUniqState();\r\n");
      out.write("								  	naver_id_login.setButton(\"green\",3,46);\r\n");
      out.write("								  	naver_id_login.setDomain(\"http://localhost:8088/Login.cd\");\r\n");
      out.write("								  	naver_id_login.setState(state);\r\n");
      out.write("								  	naver_id_login.setPopup();\r\n");
      out.write("								  	naver_id_login.init_naver_id_login();\r\n");
      out.write("							  </script>\r\n");
      out.write("							<div class=\"button-login\" align =\"center\" style=\"margin-right: -20px; display: inline-block;padding-left: 5px;\">\r\n");
      out.write("							    <a id=\"kakao-login-btn\" >\r\n");
      out.write("							    	<img src=\"image/loginimg/kakao_login_medium_narrow.png\" style=\"cursor:pointer;\" />\r\n");
      out.write("							    </a>\r\n");
      out.write("							    <script type='text/javascript'>\r\n");
      out.write("							    Kakao.init('e439bd992667016af212fb6b7dff46dd');	\r\n");
      out.write("							    //1. 로그인 시도\r\n");
      out.write("								Kakao.Auth.createLoginButton({\r\n");
      out.write("									container: '#kakao-login-btn',\r\n");
      out.write("									success: function(authObj) {							         \r\n");
      out.write("								          //2. 로그인 성공시, API 호출\r\n");
      out.write("								          Kakao.API.request({\r\n");
      out.write("								            url: '/v2/user/me',\r\n");
      out.write("								            success: function(response) {\r\n");
      out.write("											  	scope : 'account_email';        \r\n");
      out.write("										        if (response.kakao_account.gender == 'female'){\r\n");
      out.write("										        	var userGender = '01'\r\n");
      out.write("										        }else{\r\n");
      out.write("										        	var userGender = '02'\r\n");
      out.write("										        }									      								          \r\n");
      out.write("												$(\"#token\").val(response.id);\r\n");
      out.write("												$(\"#name\").val(response.properties.nickname);\r\n");
      out.write("												$(\"#gender\").val(userGender);\r\n");
      out.write("												$(\"#birthyear\").val(response.kakao_account.birthyear);\r\n");
      out.write("												$(\"#birthday\").val(response.kakao_account.birthday);\r\n");
      out.write("												$(\"#email\").val(response.kakao_account.email);\r\n");
      out.write("												$(\"#social\").val('K');											\r\n");
      out.write("												if ($(\"#token\").val != null){\r\n");
      out.write("													$(\"#socialLogin\").submit();\r\n");
      out.write("												}		              \r\n");
      out.write("								        }\r\n");
      out.write("								          });\r\n");
      out.write("								          var token = authObj.access_token\r\n");
      out.write("								          console.log(\"token >>> : \" + token);\r\n");
      out.write("								        },\r\n");
      out.write("								        fail: function(err) {\r\n");
      out.write("//								          alert(JSON.stringify(err));\r\n");
      out.write("								        }\r\n");
      out.write("								      });									        \r\n");
      out.write("\r\n");
      out.write("								</script>\r\n");
      out.write("						    </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </fieldset>	\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"login_search\">\r\n");
      out.write("                    <div class=\"id_search\">\r\n");
      out.write("                        <h4>아이디를 잊으셨나요?</h4>\r\n");
      out.write("                        <p>본인 인증 후 회원님의 아이디를 찾아 드립니다.</p>\r\n");
      out.write("                        <a href=\"FindIdForm.cd\">아이디찾기</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"pw_search\">\r\n");
      out.write("                        <h4>비밀번호를 잊으셨나요?</h4>\r\n");
      out.write("                        <p>본인 인증 후 회원님의 비밀번호를 찾아 드립니다.</p>\r\n");
      out.write("                        <a href=\"IdCheckForm.cd\">비밀번호 찾기</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("	</form>\r\n");
      out.write("	<form name=\"socialLogin\" id=\"socialLogin\" action=\"socialLogin.cd\" method=\"post\">\r\n");
      out.write("		<input type=\"hidden\" name=\"token\"     id=\"token\"     value=\"\" />\r\n");
      out.write("		<input type=\"hidden\" name=\"name\"      id=\"name\"      value=\"\" />\r\n");
      out.write("		<input type=\"hidden\" name=\"gender\"    id=\"gender\"    value=\"\" />\r\n");
      out.write("		<input type=\"hidden\" name=\"birthday\"  id=\"birthday\"  value=\"\" />\r\n");
      out.write("		<input type=\"hidden\" name=\"birthyear\" id=\"birthyear\" value=\"\" />\r\n");
      out.write("		<input type=\"hidden\" name=\"mobile\"    id=\"mobile\"    value=\"\" />\r\n");
      out.write("		<input type=\"hidden\" name=\"email\"     id=\"email\"     value=\"\" />\r\n");
      out.write("		<input type=\"hidden\" name=\"social\"    id=\"social\"    value=\"\" />\r\n");
      out.write("	</form>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
