/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2021-12-13 06:29:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.disappearance;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.catchdog.disappearance.vo.DisappearanceVO;

public final class disappearanceSelectAllForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.catchdog.disappearance.vo.DisappearanceVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>실종동물</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
 request.setCharacterEncoding("UTF-8"); 
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/include/header.jsp", out, true);
      out.write('\r');
      out.write('\n');
      out.write('	');

	
	//페이지 변수 세팅
	int pageSize= 0;
	int groupSize = 0;
	int curPage = 0;
	int totalCount = 0;
	
	Object objPaging = request.getAttribute("Pasing");
	DisappearanceVO pagingDIVO = (DisappearanceVO)objPaging;
	
	Object obj = request.getAttribute("listAll");
	List<DisappearanceVO> list= (List)obj;
	System.out.println("Obj >>> : " + list);
	int nCnt = list.size();
	System.out.println("nCnt >>> : "+ nCnt);
	
	
      out.write("\r\n");
      out.write("	<form name = \"disappearanceSelectAllForm\" id=\"disappearanceSelectAllForm\" class=\"disappearanceSelectAllForm\">\r\n");
      out.write("		<script>\r\n");
      out.write("		\r\n");
      out.write("			//입력버튼 클릭시\r\n");
      out.write("			$(document).on(\"click\", \"#I\", function(){\r\n");
      out.write("				console.log(\"sbbtn >>>> : \" );\r\n");
      out.write("				$('#disappearanceSelectAllForm').attr({\r\n");
      out.write("					'action': 'disappearanceForm.cd',\r\n");
      out.write("					'method' : 'GET',\r\n");
      out.write("					'enctype' : 'application/x-www-form-urlencoded'\r\n");
      out.write("				}).submit();	\r\n");
      out.write("			});\r\n");
      out.write("			//이미지 클릭시\r\n");
      out.write("			function disappearanceSelectAll(ele){\r\n");
      out.write("				let id = ele.id;\r\n");
      out.write("				$(\"#dinum\").val(id);\r\n");
      out.write("				//alert(\"id >>> : \" + id);\r\n");
      out.write("				\r\n");
      out.write("				$(\"#disappearanceSelectAllForm\").attr({\r\n");
      out.write("					\"action\":\"/disappearanceSelect.cd\",\r\n");
      out.write("					\"method\":\"POST\",\r\n");
      out.write("					\"enctype\":\"application/x-www-form-urlencoded\"\r\n");
      out.write("				}).submit();\r\n");
      out.write("			}\r\n");
      out.write("		</script>	\r\n");
      out.write("		<table>\r\n");
      out.write("		<thead>\r\n");
      out.write("		<tr>\r\n");
      out.write("			");

				for(int i=0; i<list.size(); i++){
					DisappearanceVO divo = list.get(i);
					String image = divo.getDiimage();
					System.out.println("image >>>> : " + image);
					
					if(i%5 == 4){
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<td><img src='/image/disappearanceimg/");
      out.print( image );
      out.write("' width=\"150\" height=\"150\"\r\n");
      out.write("				onerror=\"this.src='image/image-available.jpg'\"\r\n");
      out.write("				id=\"");
      out.print( list.get(i).getDinum() );
      out.write("\"\r\n");
      out.write("				onclick=\"disappearanceSelectAll(this)\"><br>\r\n");
      out.write("				\r\n");
      out.write("				<input type=\"text\" name=\"diname\" id=\"diname\" value=\"이름:");
      out.print(list.get(i).getDiname() );
      out.write("\" readonly><br>\r\n");
      out.write("				<input type=\"text\" name=\"diage\" id=\"diage\" value=\"나이 :");
      out.print(list.get(i).getDiage() );
      out.write("\" readonly><br>\r\n");
      out.write("				<input type=\"text\" name=\"didate\" id=\"didate\"  value=\"실종일:");
      out.print(list.get(i).getDidate() );
      out.write("\" readonly><br>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			");

				}else {
			
      out.write("\r\n");
      out.write("			<td><img src='/image/disappearanceimg/");
      out.print( image );
      out.write("' width=\"150\" height=\"150\"\r\n");
      out.write("				onerror=\"this.src='image/image-available.jpg'\"\r\n");
      out.write("				id=\"");
      out.print( list.get(i).getDinum() );
      out.write("\"\r\n");
      out.write("				onclick=\"disappearanceSelectAll(this)\"><br>\r\n");
      out.write("				\r\n");
      out.write("				<input type=\"text\" name=\"diname\" id=\"diname\" value=\"이름:");
      out.print(list.get(i).getDiname() );
      out.write("\" readonly><br>\r\n");
      out.write("				<input type=\"text\" name=\"diage\" id=\"diage\" value=\"나이 :");
      out.print(list.get(i).getDiage() );
      out.write("\" readonly><br>\r\n");
      out.write("				<input type=\"text\" name=\"didate\" id=\"didate\"  value=\"실종일:");
      out.print(list.get(i).getDidate() );
      out.write("\" readonly><br>\r\n");
      out.write("			</td>\r\n");
      out.write("\r\n");
      out.write("			");

					}
					
				}
			
      out.write("\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("		</thead>\r\n");
      out.write("\r\n");

for(int i=0; i<nCnt; i++){
		DisappearanceVO divo = list.get(i);
		pageSize = Integer.parseInt(pagingDIVO.getPageSize());
		groupSize = Integer.parseInt(pagingDIVO.getGroupSize());
		curPage = Integer.parseInt(pagingDIVO.getCurPage());
		totalCount = Integer.parseInt(divo.getTotalCount());

      out.write("\r\n");
      out.write("\r\n");
      out.write("	<tbody>\r\n");
      out.write("	");

	}//end of for
	
      out.write("\r\n");
      out.write("		<tr class=\"button\">\r\n");
      out.write("			<td colspan=\"7\" align=\"right\">\r\n");
      out.write("				<input type=\"button\" value=\"실종동물등록\" id=\"I\">\r\n");
      out.write("				<input type=\"hidden\" id=\"dinum\" name=\"dinum\" value=\"\">\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td colspan=\"7\">\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "disappearanceSelectPaging.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("url", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("disappearanceselectAll.cd", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("str", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("curPage", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(curPage ), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("pageSize", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(pageSize ), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("groupSize", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(groupSize ), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("totalCount", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(totalCount ), request.getCharacterEncoding()), out, true);
      out.write("\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		</tbody>\r\n");
      out.write("		</table>\r\n");
      out.write("	</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
