/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2021-11-01 15:06:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.mem;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class springMemForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>스프링 회원가입 폼</title>\r\n");
      out.write("\r\n");
      out.write("<script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	$(document).ready(function(){	\r\n");
      out.write("	\r\n");
      out.write("		$(\"#midbtn\").click(function(){				\r\n");
      out.write("			console.log(\"idCheck >>> : \");\r\n");
      out.write("			\r\n");
      out.write("			let midVal = $(\"#mid\").val();\r\n");
      out.write("			if (midVal == '') {\r\n");
      out.write("				alert(\"중복 체크할 아이디를 입력하세요 >>> : \");\r\n");
      out.write("				$(\"#mid\").focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		// 아이디 중복체크 Ajax 동기 방식\r\n");
      out.write("		$(document).on(\"click\", \"#midbtn\", function(){\r\n");
      out.write("			alert(\"midbtn >>> : \");\r\n");
      out.write("			syncIdCheckData();\r\n");
      out.write("		});			\r\n");
      out.write("		\r\n");
      out.write("		async function syncIdCheckData(){			\r\n");
      out.write("			\r\n");
      out.write("			let idCheckData = '';\r\n");
      out.write("			console.log('start >>> : ');\r\n");
      out.write("			\r\n");
      out.write("			var vv = $(\"#mid\").val();\r\n");
      out.write("			alert(\"vv >>> : \" + vv);\r\n");
      out.write("			\r\n");
      out.write("			idCheckData = await ajaxIdCheckData(vv);						\r\n");
      out.write("			alert(\"리턴된 데이터 >>> : \" + idCheckData);\r\n");
      out.write("			\r\n");
      out.write("			if (\"ID_YES\" == idCheckData){\r\n");
      out.write("				alert(\"아이디 사용가능 : ID_YES.\");																		\r\n");
      out.write("				$(\"#mid\").attr(\"readonly\", true);				\r\n");
      out.write("				$(\"#mid\").css('background-color','yellow');						\r\n");
      out.write("				$(\"#mpw\").focus();				\r\n");
      out.write("			}else if (\"ID_NO\" == idCheckData){\r\n");
      out.write("				alert(\"이미 아이디 사용중 : ID_NO.\");\r\n");
      out.write("				$(\"#mid\").val('');\r\n");
      out.write("				$(\"#mid\").focus();\r\n");
      out.write("			};				\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function ajaxIdCheckData(myval){\r\n");
      out.write("			alert(\"myval >>> : \" + myval);\r\n");
      out.write("			\r\n");
      out.write("			let idCheckURL = \"memIdCheck.jin\";\r\n");
      out.write("			let reqType = \"POST\";\r\n");
      out.write("			let dataParam = { mid: myval, };\r\n");
      out.write("			\r\n");
      out.write("			return $.ajax({							\r\n");
      out.write("			    url: idCheckURL\r\n");
      out.write("			   ,type: reqType\r\n");
      out.write("			   ,data: dataParam			   \r\n");
      out.write("			});\r\n");
      out.write("		}	\r\n");
      out.write("		// 아이디 중복체크 끝 =================================================\r\n");
      out.write("			\r\n");
      out.write("		// 비밀번호 체크 \r\n");
      out.write("		$(\"#pwCheck\").click(function(){\r\n");
      out.write("			console.log(\" pwCheck 함수 진입\");\r\n");
      out.write("			var pw = $(\"#mpw\").val();\r\n");
      out.write("			var pw_r = $(\"#mpw_r\").val();\r\n");
      out.write("			// var pw = document.getElementById(\"mpw\").value;\r\n");
      out.write("			// var pw_r = document.getElementById(\"mpw_r\").value;			\r\n");
      out.write("			// alert(pw + \" : \" + pw_r);\r\n");
      out.write("			if(pw == pw_r) {\r\n");
      out.write("				alert(\"비밀번호가 같습니다.\");\r\n");
      out.write("				 pw_r.val('');\r\n");
      out.write("				// document.memForm.mpw_r.value = \"\";\r\n");
      out.write("				$(\"#mgender\").focus();						\r\n");
      out.write("				return true;\r\n");
      out.write("			} else {\r\n");
      out.write("				alert(\"비밀번호가 다릅니다.\");\r\n");
      out.write("				pw.val('');\r\n");
      out.write("				pw_r.val('');\r\n");
      out.write("		\r\n");
      out.write("				pw.focus();			\r\n");
      out.write("				\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		// 성별\r\n");
      out.write("		\r\n");
      out.write("		// 생년월일\r\n");
      out.write("		$(\"#mbirth\").on(\"input\", function(){\r\n");
      out.write("			var m = $(\"#mbirth\");\r\n");
      out.write("			if (m.val().length > m.maxlength){\r\n");
      out.write("				m.value = m.value.slice(0, m.maxlength);\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("       \r\n");
      out.write("		// 월 \r\n");
      out.write("        $(\"#mbirth1\").append(\"<option value=''>월--- </option>\");\r\n");
      out.write("        for(var i = 1; i <= 12; i++){\r\n");
      out.write("        	if (i < 10){ i = '0'+i;}\r\n");
      out.write("            $(\"#mbirth1\").append(\"<option value='\"+ i +\"'>\"+ i + \"</option>\");\r\n");
      out.write("        }\r\n");
      out.write("        // 일 \r\n");
      out.write("        $(\"#mbirth2\").append(\"<option value=''>일 ---</option>\");\r\n");
      out.write("        for(var i = 1; i <= 31; i++){\r\n");
      out.write("        	if (i < 10){ i = '0'+i;}\r\n");
      out.write("            $(\"#mbirth2\").append(\"<option value='\"+ i +\"'>\"+ i + \"</option>\");\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		// 핸드폰		\r\n");
      out.write("		// 전화번호\r\n");
      out.write("		\r\n");
      out.write("		// 이메일 \r\n");
      out.write("		$('#memail2').change(function(){	\r\n");
      out.write("		$(\"#memail2 option:selected\").each(function () {\r\n");
      out.write("			if($(this).val()== '1'){ //직접입력일 경우 \r\n");
      out.write("					var aa = $(\"#memail1\").val();\r\n");
      out.write("					//alert(\"aa >>> : \" + aa);\r\n");
      out.write("					$(\"#memail1\").val(''); //값 초기화 \r\n");
      out.write("					$(\"#memail1\").attr(\"readonly\",false); //활성화 				\r\n");
      out.write("			}else{ //직접입력이 아닐경우 \r\n");
      out.write("					$(\"#memail1\").val($(this).text()); //선택값 입력 \r\n");
      out.write("					$(\"#memail1\").attr(\"readonly\",true); //비활성화 \r\n");
      out.write("			}}); \r\n");
      out.write("		}); 	\r\n");
      out.write("		\r\n");
      out.write("		// 우편번호	\r\n");
      out.write("		$(\"#zonecode\").click(function(){\r\n");
      out.write("			console.log(\"zonecode >>> : \");\r\n");
      out.write("			new daum.Postcode({\r\n");
      out.write("				oncomplete: function(data) {\r\n");
      out.write("				    $(\"#mzonecode\").val(data.zonecode); //5자리 새우편번호 사용\r\n");
      out.write("				    $(\"#mroadaddress\").val(data.roadAddress); //도로명 주소\r\n");
      out.write("				    $(\"#mjibunaddress\").val(data.jibunAddress); //지번주소			\r\n");
      out.write("				}\r\n");
      out.write("			}).open();\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		// 취미		\r\n");
      out.write("		// 소개글 		\r\n");
      out.write("		// 사진 \r\n");
      out.write("		\r\n");
      out.write("		// 폼태그 데이터 JSP 보내기 \r\n");
      out.write("		$(\"#btn\").click(function(){\r\n");
      out.write("			//alert(\"btn click() 함수 진입 >>> : \");\r\n");
      out.write("			console.log(\"btn click() 함수 진입 >>> : \");\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("			console.log(\"mnum >>> : \" + document.memForm.mnum.value);			\r\n");
      out.write("			console.log(\"mname >>> : \" + document.memForm.mname.value);\r\n");
      out.write("			console.log(\"mid >>> : \" + document.memForm.mid.value);\r\n");
      out.write("			console.log(\"mpw >>> : \" + document.memForm.mpw.value);\r\n");
      out.write("			console.log(\"mpw_r >>> : \" + document.memForm.mpw_r.value);\r\n");
      out.write("			\r\n");
      out.write("			// 성별\r\n");
      out.write("			var mgender_check = document.getElementsByName('mgender');\r\n");
      out.write("			for (var i=0; i < mgender_check.length; i++){\r\n");
      out.write("				if(mgender_check[i].checked == true){\r\n");
      out.write("					console.log(\"mgender_check[\"+i+\"].value >>> : \" + mgender_check[i].value);\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			// 생일\r\n");
      out.write("			console.log(\"mbirth >>> : \" + document.memForm.mbirth.value);\r\n");
      out.write("			console.log(\"mbirth1 >>> : \" + document.memForm.mbirth1.value);\r\n");
      out.write("			console.log(\"mbirth2 >>> : \" + document.memForm.mbirth2.value);\r\n");
      out.write("			\r\n");
      out.write("			// 핸드폰\r\n");
      out.write("			console.log(\"mhp >>> : \" + document.memForm.mhp.value);\r\n");
      out.write("			console.log(\"mhp1 >>> : \" + document.memForm.mhp1.value);\r\n");
      out.write("			console.log(\"mhp2 >>> : \" + document.memForm.mhp2.value);\r\n");
      out.write("			\r\n");
      out.write("			// 전화번호\r\n");
      out.write("			console.log(\"mtel >>> : \" + document.memForm.mtel.value);\r\n");
      out.write("			console.log(\"mte1l >>> : \" + document.memForm.mtel1.value);\r\n");
      out.write("			console.log(\"mtel2 >>> : \" + document.memForm.mtel2.value);\r\n");
      out.write("			\r\n");
      out.write("			// 이메일\r\n");
      out.write("			console.log(\"memail >>> : \" + document.memForm.memail.value);\r\n");
      out.write("			console.log(\"memail1 >>> : \" + document.memForm.memail1.value);\r\n");
      out.write("		\r\n");
      out.write("			// 주소\r\n");
      out.write("			console.log(\"mzonecode >>> : \" + document.memForm.mzonecode.value);\r\n");
      out.write("			console.log(\"mroadaddress >>> : \" + document.memForm.mroadaddress.value);\r\n");
      out.write("			console.log(\"mroadaddressdetail >>> : \" + document.memForm.mroadaddressdetail.value);\r\n");
      out.write("			console.log(\"mjibunaddress >>> : \" + document.memForm.mjibunaddress.value);\r\n");
      out.write("			\r\n");
      out.write("			// 취미			\r\n");
      out.write("			var mhobby_check = document.getElementsByName('mhobby');\r\n");
      out.write("			for (var i=0; i < mhobby_check.length; i++){\r\n");
      out.write("				if(mhobby_check[i].checked == true){\r\n");
      out.write("					console.log(\"mhobby_check[\"+i+\"].value >>> : \" + mhobby_check[i].value);\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			// 소개글\r\n");
      out.write("			console.log(\"minfo >>> : \" + document.memForm.minfo.value);			\r\n");
      out.write("			// 사진\r\n");
      out.write("			console.log(\"mphoto >>> : \" + document.memForm.mphoto.value);\r\n");
      out.write("			//############################################# END\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("					\r\n");
      out.write("			console.log(\"mnum >>> : \" + $('#mnum').val());\r\n");
      out.write("			console.log(\"mname >>> : \" + $('input[name=mname]').val());\r\n");
      out.write("			console.log(\"mid >>> : \" + $('input[name=mid]').val());\r\n");
      out.write("			console.log(\"mpw >>> : \" + $('input[name=mpw]').val());\r\n");
      out.write("			console.log(\"mpw_r >>> : \" + $('input[name=mpw_r]').val());\r\n");
      out.write("			\r\n");
      out.write("			// 성별\r\n");
      out.write("			var mgender_check = $('input:radio[name=mgender]:checked').val();\r\n");
      out.write("			console.log(\"mgender_check.value >>> : \" + mgender_check);\r\n");
      out.write("			\r\n");
      out.write("			// 생일\r\n");
      out.write("			console.log(\"mbirth >>> : \" + $('input[name=mbirth]').val());\r\n");
      out.write("			console.log(\"mbirth1 >>> : \" + $('select[name=mbirth1]').val());\r\n");
      out.write("			console.log(\"mbirth2 >>> : \" + $('select[name=mbirth2]').val());\r\n");
      out.write("			\r\n");
      out.write("			// 핸드폰\r\n");
      out.write("			console.log(\"mhp >>> : \" + $('select[name=mhp]').val());\r\n");
      out.write("			console.log(\"mhp1 >>> : \" + $('input[name=mhp1]').val());\r\n");
      out.write("			console.log(\"mhp2 >>> : \" + $('input[name=mhp2]').val());\r\n");
      out.write("			\r\n");
      out.write("			// 전화번호\r\n");
      out.write("			console.log(\"mtel >>> : \" + $('select[name=mtel]').val());\r\n");
      out.write("			console.log(\"mte1l >>> : \" + $('input[name=mtel1]').val());\r\n");
      out.write("			console.log(\"mtel2 >>> : \" + $('input[name=mtel2]').val());\r\n");
      out.write("			\r\n");
      out.write("			// 이메일\r\n");
      out.write("			console.log(\"memail >>> : \" + $('input[name=memail]').val());\r\n");
      out.write("			console.log(\"memail1 >>> : \" + $('input[name=memail1]').val());\r\n");
      out.write("		\r\n");
      out.write("			// 주소\r\n");
      out.write("			console.log(\"mzonecode >>> : \" + $('input[name=mzonecode]').val());\r\n");
      out.write("			console.log(\"mroadaddress >>> : \" + $('input[name=mroadaddress]').val());\r\n");
      out.write("			console.log(\"mroadaddressdetail >>> : \" + $('input[name=mroadaddressdetail]').val());\r\n");
      out.write("			console.log(\"mjibunaddress >>> : \" + $('input[name=mjibunaddress]').val());\r\n");
      out.write("			\r\n");
      out.write("			// 취미			\r\n");
      out.write("			var mhobby_check = $('input:checkbox[name=mhobby]').each(function(){\r\n");
      out.write("				if (this.checked == true){\r\n");
      out.write("					console.log(\"mhobby_check.value >>> : \" + this.value);\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			// 소개글\r\n");
      out.write("			console.log(\"minfo >>> : \" + $('textarea[name=minfo]').val());			\r\n");
      out.write("			// 사진\r\n");
      out.write("			console.log(\"mphoto >>> : \" + $('input[name=mphoto]').val());			\r\n");
      out.write("			//############################################# END\r\n");
      out.write("			\r\n");
      out.write("			$(\"#memForm\")\r\n");
      out.write("			.attr({\r\n");
      out.write("					\"action\":\"memInsert.jin\",\r\n");
      out.write("				    \"method\":\"POST\",\r\n");
      out.write("				    \"enctype\":\"multipart/form-data\"\r\n");
      out.write("			       })\r\n");
      out.write("			.submit();	\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("</script>	\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h3 align=\"center\">회원 가입</h3>\r\n");
      out.write("<hr>\r\n");
      out.write("<form name=\"memForm\" id=\"memForm\">\r\n");
      out.write("<table border=\"1\" align=\"center\">\r\n");
      out.write("<tr>\r\n");
      out.write("	<td colspan=\"2\" align=\"center\">					\r\n");
      out.write("		<font size=\"4\" style=\"color:blue;\">KOSMO 93기</font> \r\n");
      out.write("		<img src=\"/springHbe/img/img_mandu/ase.gif\" width=\"25\" height=\"25\" alt=\"image\">\r\n");
      out.write("	</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td>회원번호</td>\r\n");
      out.write("	<td><input type=\"text\" name=\"mnum\" id=\"mnum\" readonly/></td>\r\n");
      out.write(" </tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td>이름</td>\r\n");
      out.write("	<td><input type=\"text\" name=\"mname\" id=\"mname\"/></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<div id=\"middiv\">\r\n");
      out.write("<tr>\r\n");
      out.write("	<td>아이디</td>\r\n");
      out.write("	<td>\r\n");
      out.write("		<!-- \r\n");
      out.write("		<input type=\"text\" name=\"mid\" id=\"mid\" placeholder=\"아이디 체크\" style=\"width:100px\" />\r\n");
      out.write("		 -->		\r\n");
      out.write("		<input type=\"text\" name=\"mid\" id=\"mid\" placeholder=\"아이디 체크\" />\r\n");
      out.write("		<input type=\"button\" name=\"midbtn\" id=\"midbtn\" value=\"아이디중복확인\"  />\r\n");
      out.write("	</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</div>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td>패스워드</td>\r\n");
      out.write("	<td>\r\n");
      out.write("		<!-- \r\n");
      out.write("			<input type=\"text\" name=\"mpw\" id=\"mpw\" style=\"width:100px\"/><br/>		\r\n");
      out.write("			<input type=\"text\" id=\"mpw_r\" name=\"mpw_r\" placeholder=\"비밀번호확인\" style=\"width:100px\" />		\r\n");
      out.write("		 -->		\r\n");
      out.write("		<input type=\"text\" name=\"mpw\" id=\"mpw\" /><br/>	\r\n");
      out.write("		<input type=\"text\" id=\"mpw_r\" name=\"mpw_r\" placeholder=\"비밀번호확인\" />\r\n");
      out.write("		<input type=\"button\" value=\"비밀번호확인\" id=\"pwCheck\"/><br/>\r\n");
      out.write("	</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td>성별</td>\r\n");
      out.write("	<td> \r\n");
      out.write("		<input type=\"radio\" name=\"mgender\" id=\"mgender\" value=\"01\" checked /> 여자\r\n");
      out.write("      	<input type=\"radio\" name=\"mgender\" id=\"mgender\" value=\"02\" /> 남자\r\n");
      out.write("    </td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td>생년월일</td>\r\n");
      out.write("	<td>		\r\n");
      out.write("		<input type=\"text\" name=\"mbirth\" id=mbirth \r\n");
      out.write("		       placeholder=\"년(4자)\" maxlength=\"4\" style=\"width:50px\"/>\r\n");
      out.write("		<select name=\"mbirth1\" id=\"mbirth1\"></select>\r\n");
      out.write("        <select name=\"mbirth2\" id=\"mbirth2\"></select>\r\n");
      out.write("	</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td>핸드폰</td>\r\n");
      out.write("	<td>\r\n");
      out.write("		<select name=\"mhp\" id=\"mhp\">\r\n");
      out.write("        	<option value=\"010\">010</option>\r\n");
      out.write("        	<option value=\"011\">011</option>\r\n");
      out.write("        	<option value=\"016\">016</option>\r\n");
      out.write("        	<option value=\"017\">017</option>		        	\r\n");
      out.write("         </select>\r\n");
      out.write("         - <input type=\"text\" name=\"mhp1\" id=\"mhp1\" size=\"2\" maxlength=\"4\" />\r\n");
      out.write("         - <input type=\"text\" name=\"mhp2\" id=\"mhp2\" size=\"2\" maxlength=\"4\" />\r\n");
      out.write("	</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td>전화번호</td>\r\n");
      out.write("	<td>\r\n");
      out.write("		<select name=\"mtel\" id=\"mtel\">\r\n");
      out.write("        	<option value=\"02\">02</option>\r\n");
      out.write("        	<option value=\"031\">031</option>\r\n");
      out.write("        	<option value=\"041\">041</option>\r\n");
      out.write("        	<option value=\"051\">051</option>\r\n");
      out.write("        	<option value=\"061\">061</option>	        			       \r\n");
      out.write("         </select>\r\n");
      out.write("		- <input type=\"text\" name=\"mtel1\" id=\"mtel1\" size=\"2\" maxlength=\"4\" />\r\n");
      out.write("		- <input type=\"text\" name=\"mtel2\" id=\"mtel2\" size=\"2\" maxlength=\"4\" />\r\n");
      out.write("	</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td>이메일</td>\r\n");
      out.write("	<td>		\r\n");
      out.write("		<input type=\"text\" name=\"memail\"  id=\"memail\" style=\"width:100px\"/>\r\n");
      out.write("		@ <input type=\"text\" name=\"memail1\" id=\"memail1\" style=\"width:100px\" placeholder=\"직접입력\" />\r\n");
      out.write("		<select name=\"memail2\" id=\"memail2\">\r\n");
      out.write("        	 <option value=\"1\" selected>직접입력</option>\r\n");
      out.write("       		 <option value=\"naver.com\">naver.com</option>	       	   \r\n");
      out.write("      		 <option value=\"gmail.com\">gmail.com</option>\r\n");
      out.write("      		 <option value=\"daum.net\">daum.net</option>	       	   \r\n");
      out.write("         </select>\r\n");
      out.write("	</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write(" 	<td>주소</td>\r\n");
      out.write(" 	<td>\r\n");
      out.write(" 		<input type=\"text\" name=\"mzonecode\" id=\"mzonecode\" placeholder=\"우편번호\" style=\"width:50px\" maxlength=\"6\" >\r\n");
      out.write(" 		<input type=\"button\" name=\"zonecode\" id=\"zonecode\" value=\"우편번호 찾기\"><br>	 	\r\n");
      out.write(" 		<input type=\"text\" name=\"mroadaddress\" id=\"mroadaddress\" placeholder=\"도로명주소\" style=\"width:250px\"><br>	 	\r\n");
      out.write(" 		<input type=\"text\" name=\"mroadaddressdetail\" id=\"mroadaddressdetail\" placeholder=\"도로명주소 상세주소\" style=\"width:250px\"><br>	 	\r\n");
      out.write(" 		<input type=\"text\" name=\"mjibunaddress\" id=\"mjibunaddress\" placeholder=\"지번주소\" style=\"width:250px\">\r\n");
      out.write(" 	</td>\r\n");
      out.write("</tr>	 \r\n");
      out.write("<tr>\r\n");
      out.write("	<td>취미</td>\r\n");
      out.write("	<td> \r\n");
      out.write("		<input type=\"checkbox\" name=\"mhobby\" value=\"01\" />알고리즘		      \r\n");
      out.write("        <input type=\"checkbox\" name=\"mhobby\" value=\"02\" />코딩\r\n");
      out.write("        <input type=\"checkbox\" name=\"mhobby\" value=\"03\" />분석설계<br>\r\n");
      out.write("        <input type=\"checkbox\" name=\"mhobby\" value=\"04\" />데이터베이스\r\n");
      out.write("        <input type=\"checkbox\" name=\"mhobby\" value=\"05\" />스크립트\r\n");
      out.write("    </td>\r\n");
      out.write("</tr>	 \r\n");
      out.write("<tr>\r\n");
      out.write("	<td>소개글</td>\r\n");
      out.write("	<td>\r\n");
      out.write("		<textarea name=\"minfo\" id=\"minfo\" rows=\"5\" cols=\"50\">내 소개글					\r\n");
      out.write("		</textarea>\r\n");
      out.write("	</td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("	<td>사진</td>\r\n");
      out.write("	<td> \r\n");
      out.write("		<input type=\"file\" name=\"mphoto\"  /><br>\r\n");
      out.write("    </td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td colspan=\"2\"> 			\r\n");
      out.write("		<button type=\"button\" id=\"btn\">보내기</button>\r\n");
      out.write("		<button type=\"reset\">다시 </button>	\r\n");
      out.write("	</td>				\r\n");
      out.write("</tr>\r\n");
      out.write("</table>				 		        		     \r\n");
      out.write("</form>	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
