/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2021-12-11 09:50:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.disadoption;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.catchdog.disadoption.dao.DisadoptionDAO;
import com.catchdog.disadoption.vo.DisadoptionVO;
import java.util.List;

public final class disadoptionPwCheckForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.catchdog.disadoption.dao.DisadoptionDAO");
    _jspx_imports_classes.add("com.catchdog.disadoption.vo.DisadoptionVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
 
	// model에 담은 anum 가져오기
	String anum = request.getParameter("anum");
	System.out.println("anum >>> : " + anum);

      out.write("\r\n");
      out.write("	\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("		//비밀번호 확인\r\n");
      out.write("		$(document).on(\"click\", \"#pwbtn\", function(){\r\n");
      out.write("			// alert(\"pwbtn >>> : \");\r\n");
      out.write("\r\n");
      out.write("			let pwcheckURL = \"disadoptionPwCheck.cd\";\r\n");
      out.write("			let reqType = \"POST\";\r\n");
      out.write("			let dataParam = {\r\n");
      out.write("				// anum을 val에담고   pwcheckURL인 컨트롤러  disadoptionPwCheck로 보낸다\r\n");
      out.write("				anum: $(\"#anum\").val(),\r\n");
      out.write("				apw: $(\"#apw\").val(),\r\n");
      out.write("\r\n");
      out.write("			};\r\n");
      out.write("			//dataParam = $(\"#boardUpdateForm\")ing.serialize();\r\n");
      out.write("			//alert(\"dataParam >>> : \" + dataParam);\r\n");
      out.write("			\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url: pwcheckURL,\r\n");
      out.write("				type: reqType,	\r\n");
      out.write("				// disadoptionPwCheck컨트롤러가서 쿼리조회후  (data:dataParm) 데이터 체크 한다.\r\n");
      out.write("				data: dataParam,	            \r\n");
      out.write("				success: whenSuccess,\r\n");
      out.write("				error: whenError\r\n");
      out.write("			});\r\n");
      out.write("			// resData -> controller return값 msg \r\n");
      out.write("			function whenSuccess(resData){	\r\n");
      out.write("				alert(\"resData >>> : \" + resData);\r\n");
      out.write("				// 문자열 비교후 \"PW_GOOD\"이면 disadoptionSelect\r\n");
      out.write("				if (\"PW_GOOD\" == resData){\r\n");
      out.write("					//alert(\"비밀번호 GOOD.\");\r\n");
      out.write("					$(\"#apw\").attr(\"readonly\", true);\r\n");
      out.write("					$(\"#pwform\").attr({						\r\n");
      out.write("						'action':'disadoptionSelect.cd',\r\n");
      out.write("						'method':'POST',\r\n");
      out.write("						'enctype':'application/x-www-form-urlencoded'\r\n");
      out.write("					}).submit();\r\n");
      out.write("				}else if (\"PW_BAD\" == resData){\r\n");
      out.write("					//alert(\"비밀번호 BAD.\");\r\n");
      out.write("					$(\"#apw\").val('');\r\n");
      out.write("					$(\"#apw\").focus();\r\n");
      out.write("				};				\r\n");
      out.write("			}\r\n");
      out.write("			function whenError(e){\r\n");
      out.write("				alert(\"e >>> : \" + e.responseText);\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/include/header.jsp", out, true);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"pwform\">\r\n");
      out.write("	<form name =\"pwform\" id=\"pwform\">\r\n");
      out.write("	<p>비밀번호를 입력하세요.</p>\r\n");
      out.write("	<!-- model에서 넘어온 value의 anum값이 script val 로 간다. -->\r\n");
      out.write("	<input type=\"hidden\" id=\"anum\" name=\"anum\" value=\"");
      out.print( anum);
      out.write("\"/>\r\n");
      out.write("	<input type=\"password\" id=\"apw\" name=\"apw\"/>\r\n");
      out.write("	<button type=\"button\" id=\"pwbtn\" name=\"pwbtn\"> 확인</button>\r\n");
      out.write("	</form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
