/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2021-12-11 15:46:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.disadoption;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.catchdog.common.K_Session;
import java.util.Map;

public final class disadoptionBoardInsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.catchdog.common.K_Session");
    _jspx_imports_classes.add("java.util.Map");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    K_Session ks = K_Session.getInstance();
    Map<String,Object> ssMap = ks.getSession(request);
    String ssMname = "";
	if(ssMap.get("ssMid") != null){
		ssMap.get("ssMname");
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	//location.href=\"/disadoptionBoardInsertForm.cd\";\r\n");
      out.write("	/*\r\n");
      out.write("	 $(document).ready(function(){\r\n");
      out.write("		 $(\"#disadoptionBoardInsertForm\").attr({ \"method\":\"POST\"\r\n");
      out.write("	         ,\"action\":\"disadoptionBoardInsertForm.cd\"}).submit();\r\n");
      out.write("		});\r\n");
      out.write("	*/\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//alert(\"자바스크립트 블럭 시작 >>> : \")\r\n");
      out.write("\r\n");
      out.write("	$(document).ready(function(){	\r\n");
      out.write("		//alert(\"제이쿼리 블럭 시작 >>> : \")\r\n");
      out.write("		// 회원번호 		\r\n");
      out.write("		// 이름 \r\n");
      out.write("		\r\n");
      out.write("		// 지역\r\n");
      out.write("		$(\"#acaresite1\").on('change',function(){\r\n");
      out.write("			\r\n");
      out.write("			var idx = $(this).val(); // 첫번째 select 선택 값 가져오기\r\n");
      out.write("			\r\n");
      out.write("			$('#acaresite2').children('option:not(:first)').remove(); // 두번째 select option값 지우기 (첫번째 option 제외)\r\n");
      out.write("			\r\n");
      out.write("			for(var i=0; i<cities[idx].length; i++){ // combo1의 크기만큼 for문 반복\r\n");
      out.write("				var optiondata = cities[idx][i];\r\n");
      out.write("				$('#acaresite2').append('<option value=\"'+optiondata+'\">'+optiondata+'</option>'); // option 추가하기\r\n");
      out.write("			}	\r\n");
      out.write("			$(\"#acaresite\").val($(\"#acaresite1 option:checked\").text());\r\n");
      out.write("		});	\r\n");
      out.write("		$(\"#acaresite2\").on('change',function(){\r\n");
      out.write("			$(\"#acaresite\").val($(\"#acaresite1 option:checked\").text()+ \" \" +$(\"#acaresite2 option:checked\").text());			 \r\n");
      out.write("		});\r\n");
      out.write("		// 비밀번호 체크 \r\n");
      out.write("		$(\"#pwCheck\").click(function(){\r\n");
      out.write("			console.log(\" pwCheck 함수 진입\");\r\n");
      out.write("			var pw = $(\"#apw\").val();\r\n");
      out.write("			var pw_r = $(\"#apw_r\").val();\r\n");
      out.write("			// var pw = document.getElementById(\"mpw\").value;\r\n");
      out.write("			// var pw_r = document.getElementById(\"mpw_r\").value;			\r\n");
      out.write("			// alert(pw + \" : \" + pw_r);\r\n");
      out.write("			 if (pw == pw_r) {\r\n");
      out.write("            alert(\"비밀번호가 같습니다.\");\r\n");
      out.write("            pw_r.val('');\r\n");
      out.write("			// document.memForm.mpw_r.value = \"\";\r\n");
      out.write("			$(\"#aname\").focus();						\r\n");
      out.write("			return true;\r\n");
      out.write("		} else {\r\n");
      out.write("			alert(\"비밀번호가 다릅니다.\");\r\n");
      out.write("			pw.val('');\r\n");
      out.write("			pw_r.val('');\r\n");
      out.write("			//document.memForm.mpw.value = \"\";\r\n");
      out.write("			//document.memForm.mpw_r.value = \"\";\r\n");
      out.write("			//document.memForm.mpw.focus();\r\n");
      out.write("			pw.focus();			\r\n");
      out.write("			\r\n");
      out.write("			return false;;\r\n");
      out.write("			 }\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		// 폼태그 데이터 JSP 보내기 \r\n");
      out.write("		$(\"#btn\").click(function(){\r\n");
      out.write("			//alert(\"btn click() 함수 진입 >>> : \");\r\n");
      out.write("			console.log(\"btn click() 함수 진입 >>> : \");\r\n");
      out.write("			\r\n");
      out.write("			/* \r\n");
      out.write("			form 태그에서 서블릿으로 전송되는 데이터 \r\n");
      out.write("			콘솔에서 확인하기, alert으로 확인하기				\r\n");
      out.write("		*/\r\n");
      out.write("		\r\n");
      out.write("		//############################################# START\r\n");
      out.write("		/*\r\n");
      out.write("			자바스크립트 버전 \r\n");
      out.write("			\r\n");
      out.write("			id 값 : \r\n");
      out.write("				var v1 = document.getElementById('id_name').value;\r\n");
      out.write("			name 값 : \r\n");
      out.write("				var v2 = document.form_name.input_name.value;\r\n");
      out.write("			class 값 : \r\n");
      out.write("				var v3 = document.getElementsByName('mgender');\r\n");
      out.write("			\r\n");
      out.write("		*/		\r\n");
      out.write("		/*\r\n");
      out.write("		1. console.log() : 함수는 웹 브라우저 콘솔에 프린트 하는 함수 이다. \r\n");
      out.write("		                    System.out.println() 과 같다.\r\n");
      out.write("		2. document : <html></html>\r\n");
      out.write("		3. disadoptionBoardInsertForm : form 태그의 name 속성의 값 form name=\"disadoptionBoardInsertForm\"\r\n");
      out.write("		4. mnum : disadoptionBoardInsertForm 태그의 intpu name=\"mnum\" 속성\r\n");
      out.write("		5. value : mnum 의 값\r\n");
      out.write("		\r\n");
      out.write("		<form name=\"disadoptionBoardInsertForm\" id=\"disadoptionBoardInsertForm\">\r\n");
      out.write("			<input type=\"text\" name=\"mnum\" id=\"mnum\" readonly/>\r\n");
      out.write("		</from>\r\n");
      out.write("		*/			\r\n");
      out.write("			console.log(\"anum >>> : \" + document.disadoptionBoardInsertForm.anum.value);\r\n");
      out.write("			console.log(\"asubject >>> : \" + document.disadoptionBoardInsertForm.asubject.value);\r\n");
      out.write("			console.log(\"apw >>> : \" + document.disadoptionBoardInsertForm.apw.value);\r\n");
      out.write("			console.log(\"apw_r >>> : \" + document.disadoptionBoardInsertForm.apw_r.value);\r\n");
      out.write("			console.log(\"aname >>> : \" + document.disadoptionBoardInsertForm.aname.value);\r\n");
      out.write("		\r\n");
      out.write("			// 종구분\r\n");
      out.write("			var aupkind_check = document.getElementsByName('aupkind');\r\n");
      out.write("			for (var i=0; i < aupkind_check.length; i++){\r\n");
      out.write("				if(aupkind_check[i].checked == true){\r\n");
      out.write("					console.log(\"aupkind_check[\"+i+\"].value >>> : \" + aupkind_check[i].value);\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			// 세부종\r\n");
      out.write("			console.log(\"akind >>> : \" + document.disadoptionBoardInsertForm.akind.value);\r\n");
      out.write("			\r\n");
      out.write("			console.log(\"acolor >>> : \" + document.disadoptionBoardInsertForm.acolor.value);\r\n");
      out.write("			console.log(\"asize >>> : \" + document.disadoptionBoardInsertForm.asize.value);\r\n");
      out.write("			console.log(\"aneut >>> : \" + document.disadoptionBoardInsertForm.aneut.value);\r\n");
      out.write("			console.log(\"aage >>> : \" + document.disadoptionBoardInsertForm.aage.value);\r\n");
      out.write("			// 사진\r\n");
      out.write("			console.log(\"aimage >>> : \" + document.disadoptionBoardInsertForm.aimage.value);\r\n");
      out.write("			// 거주지역			\r\n");
      out.write("			console.log(\"acaresite >>> : \" + document.disadoptionBoardInsertForm.acaresite.value);\r\n");
      out.write("			\r\n");
      out.write("			// 보호자 연락처\r\n");
      out.write("			console.log(\"acaretel >>> : \" + document.disadoptionBoardInsertForm.acaretel.value);\r\n");
      out.write("			console.log(\"acaretel1 >>> : \" + document.disadoptionBoardInsertForm.acaretel1.value);\r\n");
      out.write("			console.log(\"acaretel2 >>> : \" + document.disadoptionBoardInsertForm.acaretel2.value);\r\n");
      out.write("	\r\n");
      out.write("			\r\n");
      out.write("			// 소개글\r\n");
      out.write("			console.log(\"aspecial >>> : \" + document.disadoptionBoardInsertForm.aspecial.value);			\r\n");
      out.write("			//############################################# END\r\n");
      out.write("			// 지역\r\n");
      out.write("			$(\"#acaresite1\").on('change',function(){\r\n");
      out.write("				\r\n");
      out.write("				var idx = $(this).val(); // 첫번째 select 선택 값 가져오기\r\n");
      out.write("				\r\n");
      out.write("				$('#acaresite2').children('option:not(:first)').remove(); // 두번째 select option값 지우기 (첫번째 option 제외)\r\n");
      out.write("				\r\n");
      out.write("				for(var i=0; i<cities[idx].length; i++){ // combo1의 크기만큼 for문 반복\r\n");
      out.write("					var optiondata = cities[idx][i];\r\n");
      out.write("					$('#acaresite2').append('<option value=\"'+optiondata+'\">'+optiondata+'</option>'); // option 추가하기\r\n");
      out.write("				}	\r\n");
      out.write("				$(\"#acaresite\").val($(\"#acaresite1 option:checked\").text());\r\n");
      out.write("			});	\r\n");
      out.write("			$(\"#acaresite2\").on('change',function(){\r\n");
      out.write("				$(\"#acaresite\").val($(\"#acaresite1 option:checked\").text()+ \" \" +$(\"#acaresite2 option:checked\").text());			 \r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			//############################################# START\r\n");
      out.write("		\r\n");
      out.write("			$(\"#disadoptionBoardInsertForm\")\r\n");
      out.write("			.attr({\r\n");
      out.write("					\"action\":\"disadoptionBoardInsertForm.cd\",\r\n");
      out.write("				    \"method\":\"POST\",\r\n");
      out.write("				    \"enctype\":\"multipart/form-data\"\r\n");
      out.write("			       })\r\n");
      out.write("			.submit();	\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("	var cities = [\r\n");
      out.write("		[\"강남구\",\"강동구\",\"강북구\",\"강서구\",\"관악구\",\"광진구\",\"구로구\",\"금천구\",\"노원구\",\"도봉구\",\"동대문구\",\"동작구\",\"마포구\",\"서대문구\",\"서초구\",\"성동구\",\"성북구\",\"송파구\",\"양천구\",\"영등포구\",\"용산구\",\"은평구\",\"종로구\",\"중구\",\"중랑구\"],\r\n");
      out.write("		[\"강서구\",\"금정구\",\"기장군\",\"남구\",\"동구\",\"동래구\",\"부산진구\",\"북구\",\"사상구\",\"사하구\",\"서구\",\"수영구\",\"연제구\",\"영도구\",\"중구\",\"해운대구\"],\r\n");
      out.write("		[\"남구\",\"달서구\",\"달성군\",\"동구\",\"북구\",\"서구\",\"수성구\",\"중구\"],\r\n");
      out.write("		[\"강화군\",\"계양구\",\"남동구\",\"동구\",\"미추홀구\",\"부평구\",\"서구\",\"연수구\",\"옹진군\",\"중구\"],\r\n");
      out.write("		[\"광산구\",\"남구\",\"동구\",\"북구\",\"서구\"],																																											\r\n");
      out.write("		[\"대덕구\",\"동구\",\"서구\",\"유성구\",\"중구\"],																																											\r\n");
      out.write("		[\"남구\",\"동구\",\"북구\",\"울주군\",\"중구\"],																																											\r\n");
      out.write("		[],\r\n");
      out.write("		[\"가평군\",\"고양시 덕양구\",\"고양시 일산동구\",\"고양시 일산서구\",\"과천시\",\"광명시\",\"광주시\",\"구리시\",\"군포시\",\"김포시\",\"남양주시\",\"동두천시\",\"부천시\",\"성남시 분당구\",\"성남시 수정구\",\"성남시 중원구\",\"수원시 권선구\",\"수원시 영통구\",\"수원시 장안구\",\"수원시 팔달구\",\"시흥시\",\"안산시 단원구\",\"안산시 상록구\",\"안성시\",\"안양시 동안구\",\"안양시 만안구\",\"양주시\",\"양평군\",\"여주시\",\"연천군\",\"오산시\",\"용인시 기흥구\",\"용인시 수지구\",\"용인시 처인구\",\"의왕시\",\"의정부시\",\"이천시\",\"파주시\",\"평택시\",\"포천시\",\"하남시\",\"화성시\"],\r\n");
      out.write("		[\"강릉시\",\"고성군\",\"동해시\",\"삼척시\",\"속초시\",\"양구군\",\"양양군\",\"영월군\",\"원주시\",\"인제군\",\"정선군\",\"철원군\",\"춘천시\",\"태백시\",\"평창군\",\"홍천군\",\"화천군\",\"횡성군\"],																																										\r\n");
      out.write("		[\"괴산군\",\"단양군\",\"보은군\",\"영동군\",\"옥천군\",\"음성군\",\"제천시\",\"증평군\",\"진천군\",\"청주시 상당구\",\"청주시 서원구\",\"청주시 청원구\",\"청원시 흥덕구\",\"충주시\"],\r\n");
      out.write("		[\"계룡시\",\"공주시\",\"금산군\",\"논산시\",\"당진시\",\"보령시\",\"부여군\",\"서산시\",\"서천군\",\"아산시\",\"예산군\",\"천안시 동남구\",\"천안시 서북구\",\"청양군\",\"태안군\",\"홍성군\"],\r\n");
      out.write("		[\"고창군\",\"군산시\",\"김제시\",\"남원시\",\"무주군\",\"부안군\",\"순창군\",\"완주군\",\"익산시\",\"임실군\",\"장수군\",\"전주시 덕진구\",\"전주시 완산구\",\"정읍시\",\"진안군\"],\r\n");
      out.write("		[\"강진군\",\"고흥군\",\"곡성군\",\"광양시\",\"구례군\",\"나주시\",\"담양군\",\"목포시\",\"무안군\",\"보성군\",\"순천시\",\"신안군\",\"여수시\",\"영광군\",\"영암군\",\"완도군\",\"장성군\",\"장흥군\",\"진도군\",\"함평군\",\"해남군\",\"화순군\"],\r\n");
      out.write("		[\"경산시\",\"경주시\",\"고령군\",\"구미시\",\"군위군\",\"김천시\",\"문경시\",\"봉화군\",\"상주시\",\"성주군\",\"안동시\",\"영덕군\",\"영양군\",\"영주시\",\"영천시\",\"예천군\",\"울릉군\",\"울진군\",\"의성군\",\"청도군\",\"청송군\",\"칠곡군\",\"포항시 남구\",\"포항시 북구\"],\r\n");
      out.write("		[\"거제시\",\"거창군\",\"고성군\",\"김해시\",\"남해군\",\"밀양시\",\"사천시\",\"산청군\",\"양산시\",\"의령군\",\"진주시\",\"창녕군\",\"창원시 마산합포구\",\"창원시 마산회원구\",\"창원시 성산구\",\"창원시 의창구\",\"창원시 진해구\",\"통영시\",\"하동군\",\"함안군\",\"함양군\",\"합천군\"],\r\n");
      out.write("		[\"서귀포시\",\"제주시\"]\r\n");
      out.write("	];\r\n");
      out.write("</script>	\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/include/header.jsp", out, true);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("<form name=\"disadoptionBoardInsertForm\" id=\"disadoptionBoardInsertForm\">\r\n");
      out.write("<table align=\"center\">\r\n");
      out.write("		<colgroup>\r\n");
      out.write("                    <col width=\"250px\">\r\n");
      out.write("                    <col width=\"*\">\r\n");
      out.write("                    </colgroup>\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		<input type=\"hidden\" name=\"anum\" id=\"anum\" readonly/>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th>제목</th>\r\n");
      out.write("		<td><input type=\"text\" name=\"asubject\" id=\"asubject\"/></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th>작성자</th>\r\n");
      out.write("		<td><input type=\"text\" name=\"mname\" id=\"mname\" value=\"");
      out.print( ssMap.get("ssMname") );
      out.write("\" readonly/></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th>글비밀번호</th>\r\n");
      out.write("			<td>\r\n");
      out.write("			<input type=\"text\" name=\"apw\" id=\"apw\" /><br/>	\r\n");
      out.write("			<input type=\"text\" id=\"apw_r\" name=\"apw_r\" placeholder=\"비밀번호확인\" />\r\n");
      out.write("			<input type=\"button\" value=\"비밀번호확인\" id=\"pwCheck\"/><br/>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th>이름</th>\r\n");
      out.write("		<td><input type=\"text\" name=\"aname\" id=\"aname\" /></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("	<th>종구분</th>\r\n");
      out.write("	<td> \r\n");
      out.write("		<input type=\"radio\" name=\"aupkind\" id=\"aupkind\" value=\"01\" checked /> 고양이\r\n");
      out.write("      	<input type=\"radio\" name=\"aupkind\" id=\"aupkind\" value=\"02\" /> 강아지\r\n");
      out.write("    </td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("	<th>세부종</th>		\r\n");
      out.write("	<td><input type=\"text\" name=\"akind\" id=\"akind\"/></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("	<th>색상</th>\r\n");
      out.write("	<td>\r\n");
      out.write("		<select name=\"acolor\" id=\"acolor\">\r\n");
      out.write("        	<option value=\"1\">흰</option>\r\n");
      out.write("        	<option value=\"2\">검</option>\r\n");
      out.write("        	<option value=\"2\">갈</option>\r\n");
      out.write("        	<option value=\"4\">노</option>		        	\r\n");
      out.write("        	<option value=\"5\">고등어</option>		        	\r\n");
      out.write("        	<option value=\"6\">주</option>		        	\r\n");
      out.write("        	<option value=\"7\">회</option>		        	\r\n");
      out.write("         </select>\r\n");
      out.write("	</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("	<th>털길이</th>\r\n");
      out.write("	<td>\r\n");
      out.write("		<select name=\"afur\" id=\"afur\">\r\n");
      out.write("        	<option value=\"01\">중장모</option>\r\n");
      out.write("        	<option value=\"02\">단모</option>\r\n");
      out.write("        	<option value=\"03\">장모</option>	        	\r\n");
      out.write("         </select>\r\n");
      out.write("	</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("	<th>크기</th>\r\n");
      out.write("	<td>\r\n");
      out.write("		<select name=\"asize\" id=\"asize\">\r\n");
      out.write("        	<option value=\"대\">대</option>\r\n");
      out.write("        	<option value=\"중\">중</option>\r\n");
      out.write("        	<option value=\"소\">소</option>	        	\r\n");
      out.write("         </select>\r\n");
      out.write("	</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("	<th>중성화 여부</th>\r\n");
      out.write("	<td>\r\n");
      out.write("		<select name=\"aneut\" id=\"aneut\">\r\n");
      out.write("        	<option value=\"유\">유</option>\r\n");
      out.write("        	<option value=\"무\">무</option>\r\n");
      out.write("        	<option value=\"미상\">미상</option>	        	\r\n");
      out.write("         </select>\r\n");
      out.write("	</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th>추정나이</th>\r\n");
      out.write("		<td><input type=\"text\" name=\"aage\" id=\"aage\"/></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("	<th>사진</th>\r\n");
      out.write("	<td> \r\n");
      out.write("		<input type=\"file\" name=\"aimage\"  /><br>\r\n");
      out.write("    </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("    <th>성별</th>\r\n");
      out.write("    <td> \r\n");
      out.write("		<input type=\"radio\" name=\"agender\" id=\"agender\" value=\"01\" checked /> 남\r\n");
      out.write("      	<input type=\"radio\" name=\"agender\" id=\"agender\" value=\"02\" /> 여\r\n");
      out.write("    </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("	<th>보호중인 장소</th>\r\n");
      out.write("	<td><input type=\"hidden\" name=\"acaresite\" id=\"acaresite\" />\r\n");
      out.write("		<select name=\"acaresite1\" id=\"acaresite1\">\r\n");
      out.write("			<option>시/도 선택</option>\r\n");
      out.write("			<option value=\"0\" title=\"서울특별시\">서울특별시</option>\r\n");
      out.write("			<option value=\"1\" title=\"부산광역시\">부산광역시</option>\r\n");
      out.write("			<option value=\"2\" title=\"대구광역시\">대구광역시</option>\r\n");
      out.write("			<option value=\"3\" title=\"인천광역시\">인천광역시</option>\r\n");
      out.write("			<option value=\"4\" title=\"광주광역시\">광주광역시</option>\r\n");
      out.write("			<option value=\"5\" title=\"대전광역시\">대전광역시</option>\r\n");
      out.write("			<option value=\"6\" title=\"울산광역시\">울산광역시</option>\r\n");
      out.write("			<option value=\"7\" title=\"세종특별자치시\">세종특별자치시</option>\r\n");
      out.write("			<option value=\"8\" title=\"경기도\">경기도</option>\r\n");
      out.write("			<option value=\"9\" title=\"강원도\">강원도</option>\r\n");
      out.write("			<option value=\"10\" title=\"충청북도\">충청북도</option>\r\n");
      out.write("			<option value=\"11\" title=\"충청남도\">충청남도</option>\r\n");
      out.write("			<option value=\"12\" title=\"전라북도\">전라북도</option>\r\n");
      out.write("			<option value=\"13\" title=\"전라남도\">전라남도</option>\r\n");
      out.write("			<option value=\"14\" title=\"경상북도\">경상북도</option>\r\n");
      out.write("			<option value=\"15\" title=\"경상남도\">경상남도</option>\r\n");
      out.write("			<option value=\"16\" title=\"제주특별자치도\">제주특별자치도</option>\r\n");
      out.write("		</select>\r\n");
      out.write("		<select name=\"acaresite2\" id=\"acaresite2\">\r\n");
      out.write("			<option value=\"선택\">시/군/구 선택</option>\r\n");
      out.write("		</select></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("	<th>보호자 전화번호</th>\r\n");
      out.write("	<td>\r\n");
      out.write("		<select name=\"acaretel\" id=\"acaretel\">\r\n");
      out.write("        	<option value=\"010\">010</option>\r\n");
      out.write("        	<option value=\"011\">011</option>        			       \r\n");
      out.write("         </select>\r\n");
      out.write("		- <input type=\"text\" name=\"acaretel1\" id=\"acaretel1\" size=\"2\" maxlength=\"4\" />\r\n");
      out.write("		- <input type=\"text\" name=\"acaretel2\" id=\"acaretel2\" size=\"2\" maxlength=\"4\" />\r\n");
      out.write("	</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("	<th>특징</th>\r\n");
      out.write("	<td>\r\n");
      out.write("		<textarea name=\"aspecial\" id=\"aspecial\" rows=\"5\" cols=\"50\"> 파양이유 , 소개 , 접종여부					\r\n");
      out.write("		</textarea>\r\n");
      out.write("	</td>\r\n");
      out.write(" 	</tr>\r\n");
      out.write("<!-- 	\r\n");
      out.write("<tr>\r\n");
      out.write("	<td>취미</td>\r\n");
      out.write("	<td> \r\n");
      out.write("		<input type=\"checkbox\" name=\"mhobby\" value=\"01\" />알고리즘		      \r\n");
      out.write("        <input type=\"checkbox\" name=\"mhobby\" value=\"02\" />코딩\r\n");
      out.write("        <input type=\"checkbox\" name=\"mhobby\" value=\"03\" />분석설계<br>\r\n");
      out.write("        <input type=\"checkbox\" name=\"mhobby\" value=\"04\" />데이터베이스\r\n");
      out.write("        <input type=\"checkbox\" name=\"mhobby\" value=\"05\" />스크립트\r\n");
      out.write("    </td>\r\n");
      out.write("</tr>\r\n");
      out.write(" -->	 \r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("	<td class=\"last\" align=\"right\" colspan=\"2\"> 			\r\n");
      out.write("		<button type=\"button\" id=\"btn\">보내기</button>\r\n");
      out.write("		<button type=\"reset\">다시 </button>	\r\n");
      out.write("	</td>				\r\n");
      out.write("</tr>\r\n");
      out.write("</table>				 		        		     \r\n");
      out.write("</form>	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
