/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2021-12-11 09:38:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.catchdog.common.K_Session;
import java.util.Map;

public final class mypageForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.catchdog.common.K_Session");
    _jspx_imports_classes.add("java.util.Map");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	K_Session ks = K_Session.getInstance();
	Map<String,Object> ssMap = ks.getSession(request);
	if(ssMap.get("ssMid") != null){
		ssMap.get("ssMname");
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("	//  회원정보 수정 눌렀을때\r\n");
      out.write("	$(document).on(\"click\", \"#btn\", function(){\r\n");
      out.write("		alert(\"회원정보수정\");\r\n");
      out.write("		alert(\"");
      out.print( ssMap.get("ssMnum") );
      out.write("\");\r\n");
      out.write("		mnum: $(\"#mnum\").val()\r\n");
      out.write("		alert($(\"#mnum\").val())\r\n");
      out.write("		$(\"#mypageForm\").attr({\r\n");
      out.write("			 \"method\":\"GET\"\r\n");
      out.write("            ,\"action\":\"memSelect.cd\"\r\n");
      out.write("            ,'enctype':'application/x-www-form-urlencoded'\r\n");
      out.write("            }).submit();\r\n");
      out.write("		\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/include/header.jsp", out, true);
      out.write("\r\n");
      out.write("	<div class=\"wrap\">\r\n");
      out.write("	  <div class=\"greenContainer\">\r\n");
      out.write(" 			<form id=\"mypageForm\">\r\n");
      out.write("		  <input type=\"hidden\" name=\"mnum\" id=\"mnum\" value=\"");
      out.print( ssMap.get("ssMnum") );
      out.write("\"/>\r\n");
      out.write("		  <div class=\"name\">");
      out.print( ssMap.get("ssMname") );
      out.write("님 환영합니다</div>\r\n");
      out.write("	      <img src=\"/image/mypage/—Pngtree—soles_6083038.png\" width=\"60\" height=\"60\" alt=\"발바닥\">      \r\n");
      out.write("	  		</form>\r\n");
      out.write("	  </div>\r\n");
      out.write("	  <div class=\"summaryContainer\">\r\n");
      out.write("	    <div class=\"item\">	        \r\n");
      out.write("	        <div class=\"number\"><input type=\"button\" value=\"회원정보수정\" id=\"btn\"></div>\r\n");
      out.write("	      </div>\r\n");
      out.write("	      <div class=\"item\">\r\n");
      out.write("	        <div class=\"number\">354</div>\r\n");
      out.write("	        <div>상품후기</div>\r\n");
      out.write("	      </div>\r\n");
      out.write("	  </div>  \r\n");
      out.write("	  <div class=\"shippingStatusContainer\">\r\n");
      out.write("	    <div class=\"title\">\r\n");
      out.write("	      주문/배송조회\r\n");
      out.write("	    </div>\r\n");
      out.write("	    <div class=\"status\">\r\n");
      out.write("	      \r\n");
      out.write("	      <div class=\"item\">\r\n");
      out.write("	        <div>\r\n");
      out.write("	          <div class=\"green number\">6</div>\r\n");
      out.write("	          <div class=\"text\">장바구니</div>\r\n");
      out.write("	        </div>\r\n");
      out.write("	        <div class=\"icon\"> > </div>\r\n");
      out.write("	      </div>     \r\n");
      out.write("	      <div class=\"item\">\r\n");
      out.write("	        <div>\r\n");
      out.write("	          <div class=\"number\">0</div>\r\n");
      out.write("	          <div class=\"text\">결제완료</div>\r\n");
      out.write("	        </div>\r\n");
      out.write("	        <div class=\"icon\"> > </div>\r\n");
      out.write("	      </div>     \r\n");
      out.write("	      <div class=\"item\">\r\n");
      out.write("	        <div>\r\n");
      out.write("	          <div class=\"green number\">1</div>\r\n");
      out.write("	          <div class=\"text\">배송중</div>\r\n");
      out.write("	        </div>\r\n");
      out.write("	        <div class=\"icon\"> > </div>\r\n");
      out.write("	      </div>     \r\n");
      out.write("	      <div class=\"item\">\r\n");
      out.write("	        <div>\r\n");
      out.write("	          <div class=\"green number\">3</div>\r\n");
      out.write("	          <div class=\"text\">구매확정</div>\r\n");
      out.write("	        </div>\r\n");
      out.write("	      </div>     \r\n");
      out.write("	      \r\n");
      out.write("	    </div>\r\n");
      out.write("	    \r\n");
      out.write("	  </div>  \r\n");
      out.write("	  <div class=\"listContainer\">\r\n");
      out.write("	    <a href=\"#\" class=\"item\">\r\n");
      out.write("	        <div class=\"icon\">ii</div>\r\n");
      out.write("	        <div class=\"text\">주문목록<span class=\"circle\"></span></div>\r\n");
      out.write("	        <div class=\"right\"> > </div>\r\n");
      out.write("	    </a>\r\n");
      out.write("	    <a href=\"#\" class=\"item\">\r\n");
      out.write("	        <div class=\"icon\">ii</div>\r\n");
      out.write("	        <div class=\"text\">상품후기</div>\r\n");
      out.write("	        <div class=\"right\"> > </div>\r\n");
      out.write("	    </a>\r\n");
      out.write("	    <a href=\"#\" class=\"item\">\r\n");
      out.write("	        <div class=\"icon\">ii</div>\r\n");
      out.write("	        <div class=\"text\">상품문의</div>\r\n");
      out.write("	        <div class=\"right\"> > </div>\r\n");
      out.write("	    </a>\r\n");
      out.write("	    <a href=\"#\" class=\"item\">\r\n");
      out.write("	        <div class=\"icon\">ii</div>\r\n");
      out.write("	        <div class=\"text\">단골상점</div>\r\n");
      out.write("	        <div class=\"right\"> > </div>\r\n");
      out.write("	    </a>\r\n");
      out.write("	    <a href=\"#\" class=\"item\">\r\n");
      out.write("	        <div class=\"icon\">ii</div>\r\n");
      out.write("	        <div class=\"text\">찜한상품</div>\r\n");
      out.write("	        <div class=\"right\"> > </div>\r\n");
      out.write("	    </a>\r\n");
      out.write("	  </div>\r\n");
      out.write("	\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
